### ISSUE TITLE
Confirm intention in templates/removeRelInds.py

### ISSUE THREAD

**Issue by getconor** [h3abionet/h3agwas#11]
Quick question about the intended behavior of `templates/removeRelInds.py`.

The line `if x in remove or y in remove : pass` doesn't actually do anything since `pass` is a null operation in Python—so it is as if the `if` didn't happen at all. 

Shouldn't the line actually be `if x in remove or y in remove : continue` if the true intention is to return control to the beginning of the loop?

**Comment by shaze** [comment]
Thanks for pointing this out -- yes. 

We are releasing  new version hopefully in the next week (merging a dev branch) and will fix by then

Scott

**Comment by shaze** [comment]
This was changed
