### ISSUE TITLE
Error executing doReport process

### ISSUE THREAD

**Issue by PhilPalmer** [h3abionet/h3agwas#18]
Hi,

If I try running the following command:
```bash
nextflow run assoc.nf --input_dir sample --input_pat sampleA --data sample/sample.phe --pheno PHE --covariates SEX -profile docker
```

I get the following error:
```
ERROR ~ Error executing process > 'doReport'

Caused by:
  Missing output file(s) `out-report.pdf` expected by process `doReport`

Command executed [/h3agwas/templates/make_assoc_report.py]:

..........

Command exit status:
  0

Command output:
  (empty)

Command error:
  sh: pdflatex: not found
  chown: unrecognized option: from
  BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.

  Usage: chown [-RhLHPcvf]... USER[:[GRP]] FILE...

  Change the owner and/or group of each FILE to USER and/or GRP

  	-R	Recurse
  	-h	Affect symlinks instead of symlink targets
  	-L	Traverse all symlinks to directories
  	-H	Traverse symlinks on command line only
  	-P	Don't traverse symlinks (default)
  	-c	List changed files
  	-v	List all files
  	-f	Hide errors

```

The following files are in the work dir:
```
cleaned-pca.pdf  input.1  out-report.tex
```

So it looks like the `doReport` process failed because the output pdf could not be made (or rather converted from the latex report). So it looks like the problem is with the `pdflatex` command in the `make_assoc_report.py` script, which I guess then calls `chown` incorrectly?

Perhaps the problem is that `pdflatex` is not installed in the `quay.io/h3abionet_org/py3plink` docker container?

I think this is the case because if I try entering the docker container interactively & typing `pdflatex` I get `bash: pdflatex: command not found`

Do you think this might be the case? Or could something else be causing the issue?

Thanks again & sorry for keep on making issues

**Comment by shaze** [comment]
No, apologies from our side for not testing thinsg properly.  Recent bug caused by a recent change.

Please pull latest version pipelien --there's a different container for the latex

Should work now

**Comment by PhilPalmer** [comment]
No worries and awesome, thanks. I've pulled your fix and the pipeline is now working
