### ISSUE TITLE
Error running association pipeline with Gemma

### ISSUE THREAD

**Issue by PhilPalmer** [h3abionet/h3agwas#20]
Hi,

Sorry for making another issue 😅 

When I try running the association pipeline with Gemma using the following command:
```
nextflow run assoc.nf --input_dir sample/ --input_pat sampleA --data sample/sample.phe --pheno PHE --covariates SEX --gemma 1 --gemma_num_cores 4 -profile docker
```

I get the following error:
```
ERROR ~ Error executing process > 'getGemmaRel (1)'

Caused by:
  Process `getGemmaRel (1)` terminated with an error exit status (127)

Command executed:

  export OPENBLAS_NUM_THREADS=4
  cat sampleA.fam |awk '{print $1"	"$2"	"0.2}' > pheno
  gemma -bfile sampleA  -gk 1 -o sampleA -p pheno -n 3

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 4: gemma: command not found
```

I think this is because the `getGemmaRel` process is using the default docker container (`quay.io/h3abionet_org/py3plink`) rather than the `gemmaImage` & so the `gemma` command cannot be found.

However, if I try changing the container to the `gemmaImage` I get a segmentation fault:
```
Caused by:
  Process `getGemmaRel (1)` terminated with an error exit status (139)

Command executed:

  export OPENBLAS_NUM_THREADS=4
  cat sampleA.fam |awk '{print $1"	"$2"	"0.2}' > pheno
  gemma -bfile sampleA  -gk 1 -o sampleA -p pheno -n 3

Command exit status:
  139

Command output:
  Reading Files ...

Command error:
  .command.sh: line 4:    34 Segmentation fault      gemma -bfile sampleA -gk 1 -o sampleA -p pheno -n 3
```

Any ideas what's causing the issue? Any help would be much appreciated.

Many thanks in advance, 
Phil

**Comment by shaze** [comment]
Dear Phil

Thanks for pointing out our config bug on docker image used

I have discussed with  @jeantristanb 

We think the primary problem is that the sample data is not ideal for gemma. 

I have also updated the gemma binary.

I am looking also at a cleaner solution and will report back

**Comment by PhilPalmer** [comment]
That's great, thanks for prompt reply as always

**Comment by shaze** [comment]
Dear Phil

Having had a look at it, some of our processes have had mission creep. I think the best is to put the  gemma processes back to quay.io/h3abionet_org/py3plink  and do a docker  pull the new version of that(Gemma being much smaller than a whole bunch of Python modules, it it is cheaper to add gemma to the python image). 

I have tested on the sample data and it runs OK though because it's so small it's hard to 100% check. I am now running on a real data set but that's likely to take many hours to finish.

Sorry about the trouble

Scott

**Comment by shaze** [comment]
Phil

Sorry for the delay. It looks like my fix worked and it should work. 

Just to recap -- no change to the actual workflow but you need to pull the new  quay.io/h3abionet_org/py3plink (I don't think this is detected automatically, so  the easiest is probably just to delete the existing image in your `~/.singularity` directory and re-run)

You coud also pull manually `singularity pull docker://quay.io/h3abionet_org/py3plink` and move it to the `~/.singularity` directory.

Also remember that the sample data is not idea for gemma 

Regards

Scott
