### ISSUE TITLE
plink-qc issues

### ISSUE THREAD

**Issue by azzaea** [h3abionet/h3agwas#21]
Hello,

Thank you for the great effort putting different aspects of GWAS analysis into handy pipelines. I'm trying out the `plink-qc` pipeline with the slurmSingularity profile. The core bioinformatics processes work as one would hope, but the pipeline fails at all the steps of generating plots. Below is an error report from such a run that fails on the `generateSnpMissingnessPlot` process:

```
Command error:
  Traceback (most recent call last):
    File ".command.sh", line 44, in <module>
      plt.savefig(args.output)
    File "/home/p287664/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 716, in savefig
      res = fig.savefig(*args, **kwargs)
    File "/home/p287664/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
      self.canvas.print_figure(fname, **kwargs)
    File "/home/p287664/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2014, in print_figure
      canvas = self._get_output_canvas(format)
    File "/home/p287664/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1950, in _get_output_canvas
      canvas_class = get_registered_canvas_class(fmt)
    File "/home/p287664/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 125, in get_registered_canvas_class
      backend_class = importlib.import_module(backend_class).FigureCanvas
    File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/p287664/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 42, in <module>
      from matplotlib import _png
  ImportError: Error relocating /home/p287664/.local/lib/python3.6/site-packages/matplotlib/.libs/libz-a147dcb0.so.1.2.3: __fprintf_chk: symbol not found


```

For completion, for now, I'm using the sample data in this repo; with nextflow version 19.04.1

And I'm attaching the complete 
[nextflow.log](https://github.com/h3abionet/h3agwas/files/3327284/nextflow.log) too.

Thank you,
Azza

**Comment by shaze** [comment]
Hi Azza
I cannot replicate this on   our machine. Could you let me know what version of Singularity and what host OS you are using so I can try test further?

Also I did an update of the underlying docker image yesteday? What version are you using? I have tried with both the old version and new version and had no problems but would like to know

What happens if you run the underlying image directly -- for example on my ssystem I do

```
[scott@n01 .singularity]$  singularity exec  quay.io-h3abionet_org-py3plink.img   bash
INFO:    Convert SIF file to sandbox...

Singularity> echo test > test
Singularity> python3 --version
Python 3.6.8
Singularity> python3
Python 3.6.8 (default, Apr 22 2019, 10:24:07) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> import matplotlib
>>> import matplotlib
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> 
>>> # Data for plotting
... t = np.arange(0.0, 2.0, 0.01)
>>> s = 1 + np.sin(2 * np.pi * t)
>>> 
>>> fig, ax = plt.subplots()
>>> ax.plot(t, s)
[<matplotlib.lines.Line2D object at 0x7ff9a268afd0>]
>>> 
>>> ax.set(xlabel='time (s)', ylabel='voltage (mV)',
...        title='About as simple as it gets, folks')
[Text(0, 0.5, 'voltage (mV)'), Text(0.5, 0, 'time (s)'), Text(0.5, 1.0, 'About as simple as it gets, folks')]
>>> ax.grid()
>>> 
>>> fig.savefig("test.png")
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> quit()
Singularity> ls
```

**Comment by shaze** [comment]
Also how have your configured singularity?  Is `setuid` enabled? Any other changes to the default singularity configuration?

**Comment by azzaea** [comment]
Thank you @shaze . I'm running on Centos 7 with Singularity 3.2.1-1.el7. I'm providing a few checks below, and my sense is that this is due to the python version inside the container.

```
p287664@peregrine p287664$  #This is me on the cluster
p287664@peregrine p287664$ whoami
p287664
p287664@peregrine p287664$ pwd
/data/p287664
p287664@peregrine p287664$ 
p287664@peregrine p287664$ singularity inspect quay.io-h3abionet_org-py3plink.img 
==labels==
org.label-schema.usage.singularity.deffile.from: quay.io/h3abionet_org/py3plink
org.label-schema.usage.singularity.version: 3.2.0-1.el7
org.label-schema.build-date: Tuesday_25_June_2019_16:9:22_CEST
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: docker
p287664@peregrine ~$ 
p287664@peregrine ~$ 
p287664@peregrine p287664$ 
p287664@peregrine p287664$ singularity exec  quay.io-h3abionet_org-py3plink.img   bash
p287664@peregrine p287664$ whoami
p287664
p287664@peregrine p287664$ pwd
/data/p287664
p287664@peregrine p287664$ python3 --version  # In your code, we see python 3.6.8
Python 3.6.3
p287664@peregrine p287664$ exit 
exit
p287664@peregrine p287664$ 
p287664@peregrine p287664$ 
p287664@peregrine p287664$ python3 --version
Python 3.6.8
p287664@peregrine p287664$ exit # This logs me of the cluster
logout
```

OS and singularity details:
```
p287664@peregrine ~$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

p287664@peregrine ~$ singularity --version
singularity version 3.2.1-1.el7
```

**Comment by azzaea** [comment]
Singularity is installed by the cluster administrator, so I don't have any control over its behaviour and settings (and I'm also not familiar with its usage, so I fear I will need a bit of guidance for checks).

Thank you again,
Azza

**Comment by shaze** [comment]
Hi Azza,

We also run Centos 7, singularity 3.2.1.-1  (3.2.1-1.osg34, to be  precise) and I can't replicate the problem 

The other questions I asked are about the contents of /etc/singularity/singularity.conf 

This is not a high secuirty file but could I suggest you Slack it for me so I can see -- it may be easier to proceed with our discussion there

Thanks

Scott

**Comment by azzaea** [comment]
Thank you @shaze . Slack it is.

Azza

**Comment by azzaea** [comment]
Solved via slack-debugging session. Main problem is that I had some locally installed python packages in my local path the collided with the paths python looks within (from the image). Backing up my `~/.local/bin` resolves the issue.
Another issue that crept in is extracting nextflow version in the final report. The pipeline assumes nextflow is already in the user's path (which is not necessarily in place), and hence it errs. A workaround is needed.

I'm closing this issue though, as the later aspect seems more of an improvement than an bug report (or at least, it deserves an issue with that title)

**Comment by shaze** [comment]
I have updated the script -- since the code was originally written, the nextflow version can be directly queried rather than having to run nextflow
