### ISSUE TITLE
batchReport.py requires additional str formatting

### ISSUE THREAD

**Issue by BobFonix** [h3abionet/h3agwas#23]
`pairA` and `pairB` for `curr` may require str formatting to work.

https://github.com/h3abionet/h3agwas/blob/525272bf49d77d98b818e9ca13758d1894587d1e/templates/batchReport.py#L339-L340

suggesting replace with: `str(pairA)` & `str(pairB)`

**Comment by shaze** [comment]
Sorry for the very slow response, but yes, good idea.
