### ISSUE TITLE
PCA plot not being included in the analysis report

### ISSUE THREAD

**Issue by gkatagi** [h3abionet/h3agwas#28]
HI,
I am trying to run of the association analysis on sample files using plink-assoc.nf. The analysis completed successfully. However, in the subsequent report generated, the PCA plot (of snps) seems to be missing.

for eg; nextflow run assoc.nf --input_pat raw-GWA-data --chi2 1 --logistic 1 --adjust 1

Can you please let me know how can we include the PCA plot in the report. ?
Although, the 'print_pca' option is set to 1,  the PCA plot is generated seperately. But its not included in the final analysis report.

**Comment by shaze** [comment]
I think the matter is resolved. I am closing this ticket -- if there are any unresolved issues here, can we discuss this via the H3A help desk where it was originally reported.
