### ISSUE TITLE
Cannot clone to Windows due to directory name

### ISSUE THREAD

**Issue by lvclark** [h3abionet/h3agwas#30]
The name `aux` is reserved in Windows: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

Therefore, it isn't possible to clone the repository to a Windows system.

Not that anyone is going to use this workflow on Windows, but this also prevents me from making edits on my local machine.

**Comment by shaze** [comment]
Have renamed it
