### ISSUE TITLE
error on running code

### ISSUE THREAD

**Issue by skr3178** [h3abionet/h3agwas#39]
`sudo ./nextflow run h3abionet/h3agwas/assoc/main.nf`

Both docker and singularity installed and nextflow also 
Error on running code:

N E X T F L O W  ~  version 22.10.0
Launching `https://github.com/h3abionet/h3agwas` [grave_stonebraker] DSL1 - revision: c8a7881a9d [master]

Unknown parameter : Check parameter <shared-storage-mount=/mnt/shared>

No phenotype given -- set params.pheno

**Comment by jeantristanb** [comment]
Dear user,
When you run assoc pipeline you need to give some arguments, like phenotype, software that you want to run, slurm, etc..
No phenotype given -- set params.pheno told you that you don't give phenotype,
you can find in https://github.com/h3abionet/h3agwas-examples an example dataset, for instance for asociation pipeline :
nextflow run  h3abionet/h3agwas/assoc/main.nf --input_dir qc/    --input_pat kgpexample  --data data/pheno/pheno_test.all   --pheno pheno_qt1,pheno_qt2  --output_dir assoc1 --output qt12 --linear 1 -profile  singularity
thank a lot to used h3agwas pipeline
