### ISSUE TITLE
Fine-mapping

### ISSUE THREAD

**Issue by ZoeGerber** [h3abionet/h3agwas#41]
Hi,

I would like to perform fine mapping analysis on a Coronary Artery Disease (CAD) dataset (GWAS file available here : https://data.mendeley.com/datasets/gbbsrpx6bs/1). Can I use your pipeline from this data ? Do I need to use plink format ? Can you give me some clues about the command line to use?

Thanks four yor help

**Comment by jeantristanb** [comment]
Hi, how are you? yes you can run for finemapping, one of most problem is what LD to used
One solution is to run with 1000Genome data using good population, let me know if you need more help

**Comment by jeantristanb** [comment]
Thank you, without more comment will close comment
