### ISSUE TITLE
Convert the Wiki to one or more doc files within a dedicated directory in the repo

### ISSUE THREAD

**Issue by getconor** [h3abionet/h3agwas#6]
Having just used the information in the Wiki to get things set up last night, I suggest converting some, if not all, of the information in the Wiki to one or more doc files within a dedicated directory in the repo. IMO, doing this would have several benefits, including:

- Converting from a GitHub Wiki to doc files within the repo itself will would make it possible to use the normal GitHub workflow and tools, for example it allow would-be contributors to use standard pull requests to submit possible improvements, and empower the project administration to use the standard GitHub workflow and tools to manage all of the documentation.
- Converting to doc files that reside in the repo, and thus come with the repo automatically when cloned, has the added advantage of making sure that everyone that clones the repo has a documentation set for that specific version already present in the repo when cloned. As it is now, since the Wiki and the rest of the repo are managed separately, not only do we have to refer back to the Wiki for documentation, but there is no guarantee that the doc "versions" match the versions of the actual repo.
- Keeping the primary documentation covering important topics of general interest, like installation and setup, within the repo itself is standard practice, with subjects of less general interest, like how to handle extreme edge cases, more often relegated into Wikis.

I would be willing to create a first draft of this over the next week or so if you're interested and barring any unforeseen demands on my time from my employer.

**Comment by shaze** [comment]
Conor,

Many thanks for your suggestion. We are at the moment busy reworking this all.  Our use of the wiki is has its problems. Another problem with the wiki is that although the wiki can be versioned, only the master branch is ever shown through the GitHub web interface.

If you would like to look at the next version, please checkout the `wits` branch. This will become the next version of the pipeline. It is currently being tested. Our group has used this for real data, and another H3A group has successfully used the pipeline too, but it needs further testing and there are known shortcomings.

The documentation is being restructured. Ignore the wiki (it's the master branch wiki). At the moment, the documentation has been put in one monolithic README file. I have tried to rewrite and rework.  Thank you for your offer to help with this and I'll definitely take you up on this. However, right at the moment, the documentation is too unstable with options and substantive explanation changing.

Sorry that all of this is moving under your feet as we speak but this has been under very active development in the last few weeks. Several of the H3A groups received genotype data for their projects in the last week of December and based on feedback we've been developing and changing things. On Monday we had our first completed feedback from another H3A groups running one of the new pipelines so I haven't looked at publicising this new branch more.

**Comment by getconor** [comment]
Thanks very much for the update and the tips! I'll close the two issues I opened about the documentation, and I'll hold off on opening any additional issues until things setttle down.
